### PR TITLE
Add options for Coldest, Raniest, Snowiest to idiv_various

### PR DESCRIPTION
**Pull request by iancw**
These rank individual athletes based on coldest ride, ride
 with most rain, and ride with most snow.  They show up as
 new options under Leaderboards -> Individual (various).

raniest
options
coldest

### CODE REVIEW

**Comment by hozn** [comment]
Brilliant, thanks!

**Comment by hozn** [comment]
Unfortunately, I think some of my js reorganization yesterday must have broken the leaderboard charting.  (Probably just need to move the js back into the header; putting it at the end of the doc helps with page loads, but may be producing some undesired interactions on that page.)

**Comment by jrenaut** [comment]
I've had issues with JS files at the end too. Awesome to see new stuff
popping up, hope to have some time to mess around with the site soon.

**Comment by hozn** [comment]
Yeah, I went ahead and moved them up -- looks good now.  Thanks for adding these new charts.

**Pull request merged**
